name: NapThe
main: com.gmail.vkhanh234.napthe.NapThe
version: ${project.version}
softdepend: [PlaceholderAPI]
commands:
   NapThe:
      usage: /napthe
permissions:
    NapThe.command:
      children:
        NapThe.command.choose: true
        NapThe.command.price: true
        NapThe.command.info: true
        NapThe.command.history: true
        NapThe.command.top: true
        NapThe.command.status: true
        NapThe.command.redeem: true
      description: Allows you to use basic commands.
      default: true
    NapThe.admin:
      children:
        NapThe.command.*: true
      description: Allows you to use admin's commands.
      default: op